repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [ '--maxkb=1000' ]
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: pretty-format-json
        args: [ '--autofix' ]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.3.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []

- repo: https://github.com/asottile/pyupgrade
  rev: v3.0.0
  hooks:
    - id: pyupgrade
      args: [--py37-plus]

- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.3.0
  hooks:
    - id: python-safety-dependencies-check
      args: [--ignore=51457]

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "0.3.5"
  hooks:
    - id: pyproject-fmt

- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.1
  hooks:
    - id: pycln
      args: [--all]
      stages: [manual]

- repo: https://github.com/asottile/yesqa
  rev: v1.4.0
  hooks:
    - id: yesqa
      additional_dependencies: &flake8-dependencies
        - flake8-bugbear

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      args: [ "-c", "pyproject.toml" ]
      additional_dependencies: [ "bandit[toml]" ]

- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: poetry run isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black
    types: [python]
#
#  - id: mypy
#    name: mypy
#    stages: [commit]
#    language: system
#    entry: poetry run mypy
#    args: ["--install-types", "--non-interactive"]
#    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: poetry run flake8
    types: [python]
    exclude: setup.py

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.1
  hooks:
    - id: codespell

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
    - id: python-check-blanket-noqa
    # - id: python-check-blanket-type-ignore
    - id: python-no-log-warn
      exclude: ^tests/test_sessions.py$
    - id: python-no-eval
      exclude: ^nox/manifest.py$
    - id: python-use-type-annotations
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
