on:
  push:
    branches:
      - master

jobs:
  release-on-push:
    # if: ${{ contains(github.event.label.name, 'preminor') }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Get poetry release
        run: |
          RELEASE_VER=$(poetry version | cut -d ' ' -f 2)
          export RELEASE_VER=${RELEASE_VER}
          echo "::set-env name=RELEASE_VER::$RELEASE_VER"
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          release_name: "Release ${RELEASE_VER}"
          release_body: "Additional Release Info"
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
